openapi: 3.0.1
info:
  title: Partners
  description: ''
  contact:
    name: The API Practice
  license:
    name: Private
  version: 1.0.0.14
servers:
  - url: '{protocol}://api.flowstep.dev{basePath}'
    variables:
      basePath:
        default: /api/v1/partners
      protocol:
        default: http
        enum:
          - https
  - url: 'https://api.flowstep.com/api/mock/set/08d865d4-f964-e1bc-5928-105bfb479158'
paths:
  /:
    get:
      tags:
        - Partners
      summary: Lists the partners
      description: ''
      operationId: listPartners
      parameters:
        - name: keyword
          in: query
          schema:
            title: Keyword
            type: string
            example: partner
        - name: limit
          in: query
          schema:
            title: Limit
            type: integer
            example: 20
        - name: offset
          in: query
          schema:
            title: Offset
            type: integer
            example: 0
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  total:
                    title: Total items
                    minimum: 1
                    type: integer
                    example: 10
                  items:
                    title: Items
                    type: array
                    items:
                      $ref: '#/components/schemas/PartnerModel'
    post:
      tags:
        - Partners
      summary: Create partner
      description: ''
      operationId: createPartner
      requestBody:
        content:
          application/json:
            schema:
              title: Partner Model
              type: object
              properties:
                name:
                  title: Partner Name
                  type: string
                  example: "The API Practice\_\_"
                partnerCode:
                  title: Partner Code
                  maxLength: 10
                  minLength: 2
                  type: string
                  example: TAPIP
                contactFirstName:
                  title: Contact First Name
                  type: string
                  example: David
                contactLastName:
                  title: Contact Last Name
                  type: string
                  example: Yonan
                contactPhone:
                  title: Contact Phone
                  type: string
                  example: 0928332132
                contactEmail:
                  title: Contact Email
                  type: string
                  example: david@theapipractice.com
                country:
                  title: Country
                  type: string
                  example: AU
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerModel'
  '/{id}':
    get:
      tags:
        - Partners
      summary: Get Partner by ID
      description: ''
      operationId: getPartnerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            title: Id
            type: string
            example: d116db0d-d785-418d-8fad-75d33f221540
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerModel'
    put:
      tags:
        - Partners
      summary: Update Partner by ID
      description: ''
      operationId: updatePartnerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            title: Id
            type: string
            example: d116db0d-d785-418d-8fad-75d33f221540
      requestBody:
        content:
          application/json:
            schema:
              title: Partner Model
              type: object
              properties:
                name:
                  title: Partner Name
                  type: string
                  example: "The API Practice\_\_"
                partnerCode:
                  title: Partner Code
                  maxLength: 10
                  minLength: 2
                  type: string
                  example: TAPIP
                contactFirstName:
                  title: Contact First Name
                  type: string
                  example: David
                contactLastName:
                  title: Contact Last Name
                  type: string
                  example: Yonan
                contactPhone:
                  title: Contact Phone
                  type: string
                  example: 0928332132
                contactEmail:
                  title: Contact Email
                  type: string
                  example: david@theapipractice.com
                country:
                  title: Country
                  type: string
                  example: AU
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerModel_v8'
    post:
      tags:
        - Partners
      summary: Delete by Id
      description: ''
      operationId: deleteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            title: Id
            type: string
            example: d116db0d-d785-418d-8fad-75d33f221540
      requestBody:
        content:
          application/json:
            schema:
              title: ''
              type: object
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
  '/{id}/clients':
    get:
      tags:
        - Partners
      summary: Get clients by partner id
      description: ''
      operationId: getClientsByPartnerId
      parameters:
        - name: keyword
          in: query
          schema:
            title: Keyword
            type: string
            example: partner
        - name: limit
          in: query
          schema:
            title: Limit
            type: integer
            example: 20
        - name: offset
          in: query
          schema:
            title: Offset
            type: integer
            example: 0
        - name: id
          in: path
          required: true
          schema:
            title: Id
            type: string
            example: d116db0d-d785-418d-8fad-75d33f221540
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                title: ''
                type: object
                properties:
                  total:
                    title: Total
                    type: string
                    example: '10'
                  items:
                    title: Items
                    type: array
                    items:
                      $ref: '#/components/schemas/ClientModel'
  '/code/{partnerCode}':
    get:
      tags:
        - Partners
      summary: Get by code
      description: ''
      operationId: getByCode
      parameters:
        - name: partnerCode
          in: path
          required: true
          schema:
            title: Partner Code
            maxLength: 10
            minLength: 2
            type: string
            example: TAPIP
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerModel'
components:
  schemas:
    PartnerModel:
      title: Partner Model
      type: object
      properties:
        partnerId:
          title: Partner Id
          type: string
          example: d116db0d-d785-418d-8fad-75d33f221540
        name:
          title: Partner Name
          type: string
          example: "The API Practice\_\_"
        partnerCode:
          title: Partner Code
          maxLength: 10
          minLength: 2
          type: string
          example: TAPIP
        contactFirstName:
          title: Contact First Name
          type: string
          example: David
        contactLastName:
          title: Contact Last Name
          type: string
          example: Yonan
        contactPhone:
          title: Contact Phone
          type: string
          example: 0928332132
        contactEmail:
          title: Contact Email
          type: string
          example: david@theapipractice.com
        country:
          title: Country
          type: string
          example: AU
        numberOfClients:
          title: Number Of Clients
          type: integer
          example: 4
        createdBy:
          title: Created By
          type: string
          example: Khai Nguyen
        createdDate:
          title: Created Date
          type: string
          example: '2020-09-20'
        updatedBy:
          title: Updated By
          type: string
          example: Khai Nguyen
        updatedDate:
          title: Updated Date
          type: string
          example: '2020-09-20'
    PartnerModel_v8:
      title: Partner Model
      type: object
      properties:
        id:
          title: Id
          type: string
          example: d116db0d-d785-418d-8fad-75d33f221540
        name:
          title: Partner Name
          type: string
          example: "The API Practice\_\_"
        partnerCode:
          title: Partner Code
          maxLength: 10
          minLength: 2
          type: string
          example: TAPIP
        contactFirstName:
          title: Contact First Name
          type: string
          example: David
        contactLastName:
          title: Contact Last Name
          type: string
          example: Yonan
        contactPhone:
          title: Contact Phone
          type: string
          example: 0928332132
        contactEmail:
          title: Contact Email
          type: string
          example: david@theapipractice.com
        country:
          title: Country
          type: string
          example: AU
        numberOfOrganizations:
          title: Number of Organizations
          type: integer
          example: 1
        numberOfProjects:
          title: Number of Projects
          type: integer
          example: 5
        createdDate:
          title: Created Date
          type: string
          example: '2020-09-20'
        updatedDate:
          title: Updated Date
          type: string
          example: '2020-09-20'
        createdBy:
          title: Created By
          type: string
          example: Khai Nguyen
        updatedBy:
          title: Updated By
          type: string
          example: Khai Nguyen
    ClientModel:
      title: Client Model
      type: object
      properties:
        clientId:
          title: Client Id
          type: string
          example: 5bc9572c-3ab4-42b8-a43a-384a65292bc8
        name:
          title: Client Name
          type: string
          example: Flow Step
        contactFirstName:
          title: Contact First Name
          type: string
          example: David
        contactLastName:
          title: Contact Last Name
          type: string
          example: Yonan
        contactPhone:
          title: Contact Phone
          type: string
          example: 0928332132
        contactEmail:
          title: Contact Email
          type: string
          example: david@theapipractice.com
        domainNameUrl:
          title: Domain Name Url
          type: string
          example: 'http://flowstep.com'
        country:
          title: Country
          type: string
          example: AU
        clientCode:
          title: Client Code
          type: string
          example: FS
        partnerId:
          title: Partner Id
          type: string
          example: d116db0d-d785-418d-8fad-75d33f221540
        numberOfOrganizations:
          title: Number of Organizations
          type: integer
          example: 1
        numberOfProjects:
          title: Number of Projects
          type: integer
          example: 5
        createdDate:
          title: Created Date
          type: string
          example: '2020-09-20'
        updatedDate:
          title: Updated Date
          type: string
          example: '2020-09-20'
        createdBy:
          title: Created By
          type: string
          example: Khai Nguyen
        updatedBy:
          title: Updated By
          type: string
          example: Khai Nguyen
